{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vulnerable-app.serviceAccountName" . }}
  labels:
    {{- include "vulnerable-app.labels" . | nindent 4 }}
# Issue: automountServiceAccountToken should be false at SA level too
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
