apiVersion: v1
kind: Namespace
metadata:
  name: zelyo
  labels:
    name: zelyo
    pod-security.kubernetes.io/enforce: privileged
    # Kubescape needs privileges to scan host etc if we want full deep scan, 
    # though for config scan 'restricted' might be okay but let's be safe for now 
    # as the scanner often needs some access.
