apiVersion: v1
kind: Service
metadata:
  name: zelyo-service
  namespace: zelyo
spec:
  selector:
    app: zelyo-guardian
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8086
  type: LoadBalancer # Or ClusterIP if internal only
