{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "zelyo-guardian.fullname" . }}-scanner
  labels:
    {{- include "zelyo-guardian.labels" . | nindent 4 }}
rules:
  # Kubescape needs read access to almost everything to scan configurations
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "zelyo-guardian.fullname" . }}-scanner-binding
  labels:
    {{- include "zelyo-guardian.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "zelyo-guardian.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "zelyo-guardian.fullname" . }}-scanner
  apiGroup: rbac.authorization.k8s.io
{{- end }}
